// This file is auto-generated by @hey-api/openapi-ts

export const AccountResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        current_balance: {
            '$ref': '#/components/schemas/MoneyResponse'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        },
        opened_on: {
            type: 'string',
            format: 'date',
            title: 'Opened On'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        },
        created_on: {
            type: 'string',
            format: 'date',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date',
            title: 'Updated On'
        }
    },
    type: 'object',
    required: ['id', 'name', 'type', 'currency', 'current_balance', 'opened_on', 'created_on', 'updated_on'],
    title: 'AccountResponse'
} as const;

export const AccountTypeSchema = {
    type: 'string',
    enum: ['cash', 'debit_card', 'credit_card', 'bank_account', 'wallet', 'system'],
    title: 'AccountType'
} as const;

export const CreateAccountRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType',
            default: 'debit_card'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency',
            default: 'ARS'
        },
        opening_balance_minor: {
            type: 'integer',
            title: 'Opening Balance Minor',
            default: 0
        },
        opened_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opened On'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateAccountRequest'
} as const;

export const CreateIncomeCategoryRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateIncomeCategoryRequest'
} as const;

export const CreateSpendingCategoryRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateSpendingCategoryRequest'
} as const;

export const CreateTransactionPostingRequestSchema = {
    properties: {
        account_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        amount_minor: {
            type: 'integer',
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'CreateTransactionPostingRequest'
} as const;

export const CreateTransactionRequestSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        postings: {
            items: {
                '$ref': '#/components/schemas/CreateTransactionPostingRequest'
            },
            type: 'array',
            minItems: 1,
            title: 'Postings'
        },
        occurred_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Occurred On'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        merchant_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Merchant Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['type', 'postings'],
    title: 'CreateTransactionRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        app_name: {
            type: 'string',
            title: 'App Name'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: ['status', 'app_name', 'environment'],
    title: 'HealthResponse'
} as const;

export const IncomeCategoryResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/IncomeCategoryResponse'
            },
            type: 'array',
            title: 'Children'
        }
    },
    type: 'object',
    required: ['id', 'name', 'parent_id', 'sort_order'],
    title: 'IncomeCategoryResponse'
} as const;

export const MoneyResponseSchema = {
    properties: {
        amount_minor: {
            type: 'integer',
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'MoneyResponse'
} as const;

export const PostingResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        account_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        amount_minor: {
            type: 'integer',
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        }
    },
    type: 'object',
    required: ['id', 'amount_minor', 'currency'],
    title: 'PostingResponse'
} as const;

export const SpendingCategoryResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/SpendingCategoryResponse'
            },
            type: 'array',
            title: 'Children'
        }
    },
    type: 'object',
    required: ['id', 'name', 'parent_id', 'sort_order'],
    title: 'SpendingCategoryResponse'
} as const;

export const TransactionResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        occurred_on: {
            type: 'string',
            format: 'date',
            title: 'Occurred On'
        },
        posted_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Posted On'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        merchant_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Merchant Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        status: {
            '$ref': '#/components/schemas/TransactionStatus'
        },
        type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        postings: {
            items: {
                '$ref': '#/components/schemas/PostingResponse'
            },
            type: 'array',
            title: 'Postings'
        },
        created_on: {
            type: 'string',
            format: 'date',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date',
            title: 'Updated On'
        }
    },
    type: 'object',
    required: ['id', 'occurred_on', 'status', 'type', 'postings', 'created_on', 'updated_on'],
    title: 'TransactionResponse'
} as const;

export const TransactionStatusSchema = {
    type: 'string',
    enum: ['pending', 'posted', 'void'],
    title: 'TransactionStatus'
} as const;

export const TransactionTypeSchema = {
    type: 'string',
    enum: ['expense', 'income', 'transfer', 'adjustment'],
    title: 'TransactionType'
} as const;

export const UpdateAccountProfileRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'UpdateAccountProfileRequest'
} as const;

export const UpdateIncomeCategoryRequestSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        }
    },
    type: 'object',
    title: 'UpdateIncomeCategoryRequest'
} as const;

export const UpdateSpendingCategoryRequestSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        }
    },
    type: 'object',
    title: 'UpdateSpendingCategoryRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;