// This file is auto-generated by @hey-api/openapi-ts

export const AccountResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        current_balance: {
            '$ref': '#/components/schemas/MoneyResponse'
        },
        status: {
            '$ref': '#/components/schemas/AccountStatus'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        },
        opened_on: {
            type: 'string',
            format: 'date',
            title: 'Opened On'
        },
        closed_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed On'
        },
        created_on: {
            type: 'string',
            format: 'date',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date',
            title: 'Updated On'
        }
    },
    type: 'object',
    required: ['id', 'name', 'type', 'currency', 'current_balance', 'status', 'opened_on', 'created_on', 'updated_on'],
    title: 'AccountResponse'
} as const;

export const AccountStatusSchema = {
    type: 'string',
    enum: ['active', 'closed'],
    title: 'AccountStatus'
} as const;

export const AccountTypeSchema = {
    type: 'string',
    enum: ['card', 'cash', 'bank', 'wallet', 'platform', 'savings', 'other'],
    title: 'AccountType'
} as const;

export const CreateAccountRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType',
            default: 'card'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency',
            default: 'ARS'
        },
        current_balance_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Current Balance Minor',
            default: 0
        },
        opened_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opened On'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateAccountRequest'
} as const;

export const CreateSpendingCategoryRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateSpendingCategoryRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        app_name: {
            type: 'string',
            title: 'App Name'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: ['status', 'app_name', 'environment'],
    title: 'HealthResponse'
} as const;

export const MoneyRequestSchema = {
    properties: {
        amount_minor: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'MoneyRequest'
} as const;

export const MoneyResponseSchema = {
    properties: {
        amount_minor: {
            type: 'integer',
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'MoneyResponse'
} as const;

export const SpendingCategoryResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/SpendingCategoryResponse'
            },
            type: 'array',
            title: 'Children'
        }
    },
    type: 'object',
    required: ['id', 'name', 'parent_id', 'sort_order'],
    title: 'SpendingCategoryResponse'
} as const;

export const UpdateAccountProfileRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        color_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Key'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'UpdateAccountProfileRequest'
} as const;

export const UpdateSpendingCategoryRequestSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        }
    },
    type: 'object',
    title: 'UpdateSpendingCategoryRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;