// This file is auto-generated by @hey-api/openapi-ts

export const CardCreateRequestSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency',
            default: 'ARS'
        },
        opened_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opened On'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CardCreateRequest'
} as const;

export const CardResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        balance: {
            '$ref': '#/components/schemas/MoneyResponse'
        },
        created_on: {
            type: 'string',
            format: 'date',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['id', 'name', 'currency', 'balance', 'created_on'],
    title: 'CardResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        app_name: {
            type: 'string',
            title: 'App Name'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: ['status', 'app_name', 'environment'],
    title: 'HealthResponse'
} as const;

export const MoneyRequestSchema = {
    properties: {
        amount_minor: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'MoneyRequest'
} as const;

export const MoneyResponseSchema = {
    properties: {
        amount_minor: {
            type: 'integer',
            title: 'Amount Minor'
        },
        currency: {
            type: 'string',
            minLength: 1,
            title: 'Currency'
        }
    },
    type: 'object',
    required: ['amount_minor', 'currency'],
    title: 'MoneyResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;