// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CardsListCardsResponse, CardsCreateCardData, CardsCreateCardResponse, CardsGetCardData, CardsGetCardResponse, CardsDepositToCardData, CardsDepositToCardResponse, CardsWithdrawFromCardData, CardsWithdrawFromCardResponse, SystemGetHealthResponse } from './types.gen';

export class CardsService {
    /**
     * List Cards
     * @returns CardResponse Successful Response
     * @throws ApiError
     */
    public static listCards(): CancelablePromise<CardsListCardsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cards'
        });
    }
    
    /**
     * Create Card
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CardResponse Successful Response
     * @throws ApiError
     */
    public static createCard(data: CardsCreateCardData): CancelablePromise<CardsCreateCardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cards',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Card
     * @param data The data for the request.
     * @param data.cardId
     * @returns CardResponse Successful Response
     * @throws ApiError
     */
    public static getCard(data: CardsGetCardData): CancelablePromise<CardsGetCardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cards/{card_id}',
            path: {
                card_id: data.cardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Deposit To Card
     * @param data The data for the request.
     * @param data.cardId
     * @param data.requestBody
     * @returns CardResponse Successful Response
     * @throws ApiError
     */
    public static depositToCard(data: CardsDepositToCardData): CancelablePromise<CardsDepositToCardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cards/{card_id}/deposits',
            path: {
                card_id: data.cardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Withdraw From Card
     * @param data The data for the request.
     * @param data.cardId
     * @param data.requestBody
     * @returns CardResponse Successful Response
     * @throws ApiError
     */
    public static withdrawFromCard(data: CardsWithdrawFromCardData): CancelablePromise<CardsWithdrawFromCardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cards/{card_id}/withdrawals',
            path: {
                card_id: data.cardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SystemService {
    /**
     * Get Health
     * @returns HealthResponse Successful Response
     * @throws ApiError
     */
    public static getHealth(): CancelablePromise<SystemGetHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health'
        });
    }
}