// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { SystemGetHealthData, SystemGetHealthResponses, AccountsListAccountsData, AccountsListAccountsResponses, AccountsCreateAccountData, AccountsCreateAccountResponses, AccountsCreateAccountErrors, AccountsGetAccountData, AccountsGetAccountResponses, AccountsGetAccountErrors, AccountsUpdateAccountProfileData, AccountsUpdateAccountProfileResponses, AccountsUpdateAccountProfileErrors, AccountsDepositToAccountData, AccountsDepositToAccountResponses, AccountsDepositToAccountErrors, AccountsWithdrawFromAccountData, AccountsWithdrawFromAccountResponses, AccountsWithdrawFromAccountErrors, AccountsCloseAccountData, AccountsCloseAccountResponses, AccountsCloseAccountErrors, SpendingCategoriesListSpendingCategoriesData, SpendingCategoriesListSpendingCategoriesResponses, SpendingCategoriesCreateSpendingCategoryData, SpendingCategoriesCreateSpendingCategoryResponses, SpendingCategoriesCreateSpendingCategoryErrors, SpendingCategoriesUpdateSpendingCategoryData, SpendingCategoriesUpdateSpendingCategoryResponses, SpendingCategoriesUpdateSpendingCategoryErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SystemService {
    /**
     * Get Health
     */
    public static systemGetHealth<ThrowOnError extends boolean = false>(options?: Options<SystemGetHealthData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<SystemGetHealthResponses, unknown, ThrowOnError>({
            url: '/api/v1/health',
            ...options
        });
    }
}

export class AccountsService {
    /**
     * List Accounts
     */
    public static accountsListAccounts<ThrowOnError extends boolean = false>(options?: Options<AccountsListAccountsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<AccountsListAccountsResponses, unknown, ThrowOnError>({
            url: '/api/v1/accounts',
            ...options
        });
    }
    
    /**
     * Create Account
     */
    public static accountsCreateAccount<ThrowOnError extends boolean = false>(options: Options<AccountsCreateAccountData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<AccountsCreateAccountResponses, AccountsCreateAccountErrors, ThrowOnError>({
            url: '/api/v1/accounts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Account
     */
    public static accountsGetAccount<ThrowOnError extends boolean = false>(options: Options<AccountsGetAccountData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<AccountsGetAccountResponses, AccountsGetAccountErrors, ThrowOnError>({
            url: '/api/v1/accounts/{account_id}',
            ...options
        });
    }
    
    /**
     * Update Account Profile
     */
    public static accountsUpdateAccountProfile<ThrowOnError extends boolean = false>(options: Options<AccountsUpdateAccountProfileData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<AccountsUpdateAccountProfileResponses, AccountsUpdateAccountProfileErrors, ThrowOnError>({
            url: '/api/v1/accounts/{account_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Deposit To Account
     */
    public static accountsDepositToAccount<ThrowOnError extends boolean = false>(options: Options<AccountsDepositToAccountData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<AccountsDepositToAccountResponses, AccountsDepositToAccountErrors, ThrowOnError>({
            url: '/api/v1/accounts/{account_id}/deposits',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Withdraw From Account
     */
    public static accountsWithdrawFromAccount<ThrowOnError extends boolean = false>(options: Options<AccountsWithdrawFromAccountData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<AccountsWithdrawFromAccountResponses, AccountsWithdrawFromAccountErrors, ThrowOnError>({
            url: '/api/v1/accounts/{account_id}/withdrawals',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Close Account
     */
    public static accountsCloseAccount<ThrowOnError extends boolean = false>(options: Options<AccountsCloseAccountData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<AccountsCloseAccountResponses, AccountsCloseAccountErrors, ThrowOnError>({
            url: '/api/v1/accounts/{account_id}/close',
            ...options
        });
    }
}

export class SpendingCategoriesService {
    /**
     * List Spending Categories
     */
    public static spendingCategoriesListSpendingCategories<ThrowOnError extends boolean = false>(options?: Options<SpendingCategoriesListSpendingCategoriesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<SpendingCategoriesListSpendingCategoriesResponses, unknown, ThrowOnError>({
            url: '/api/v1/spending-categories',
            ...options
        });
    }
    
    /**
     * Create Spending Category
     */
    public static spendingCategoriesCreateSpendingCategory<ThrowOnError extends boolean = false>(options: Options<SpendingCategoriesCreateSpendingCategoryData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<SpendingCategoriesCreateSpendingCategoryResponses, SpendingCategoriesCreateSpendingCategoryErrors, ThrowOnError>({
            url: '/api/v1/spending-categories',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Spending Category
     */
    public static spendingCategoriesUpdateSpendingCategory<ThrowOnError extends boolean = false>(options: Options<SpendingCategoriesUpdateSpendingCategoryData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<SpendingCategoriesUpdateSpendingCategoryResponses, SpendingCategoriesUpdateSpendingCategoryErrors, ThrowOnError>({
            url: '/api/v1/spending-categories/{category_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}