// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccountResponse
 */
export type AccountResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Currency
     */
    currency: string;
    current_balance: MoneyResponse;
    /**
     * Color Key
     */
    color_key?: string | null;
    /**
     * Opened On
     */
    opened_on: string;
    /**
     * Archived At
     */
    archived_at?: string | null;
    /**
     * Created On
     */
    created_on: string;
    /**
     * Updated On
     */
    updated_on: string;
};

/**
 * AccountType
 */
export type AccountType = 'cash' | 'debit_card' | 'credit_card' | 'bank_account' | 'wallet' | 'system';

/**
 * CreateAccountRequest
 */
export type CreateAccountRequest = {
    /**
     * Name
     */
    name: string;
    type?: AccountType;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Opening Balance Minor
     */
    opening_balance_minor?: number;
    /**
     * Opened On
     */
    opened_on?: string | null;
    /**
     * Color Key
     */
    color_key?: string | null;
};

/**
 * CreateIncomeCategoryRequest
 */
export type CreateIncomeCategoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * CreateSpendingCategoryRequest
 */
export type CreateSpendingCategoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * CreateTransactionPostingRequest
 */
export type CreateTransactionPostingRequest = {
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Memo
     */
    memo?: string | null;
};

/**
 * CreateTransactionRequest
 */
export type CreateTransactionRequest = {
    type: TransactionType;
    /**
     * Postings
     */
    postings: Array<CreateTransactionPostingRequest>;
    /**
     * Occurred On
     */
    occurred_on?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Merchant Name
     */
    merchant_name?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * App Name
     */
    app_name: string;
    /**
     * Environment
     */
    environment: string;
};

/**
 * IncomeCategoryResponse
 */
export type IncomeCategoryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Children
     */
    children?: Array<IncomeCategoryResponse>;
};

/**
 * MoneyResponse
 */
export type MoneyResponse = {
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Currency
     */
    currency: string;
};

/**
 * PostingResponse
 */
export type PostingResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Memo
     */
    memo?: string | null;
};

/**
 * SpendingCategoryResponse
 */
export type SpendingCategoryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Children
     */
    children?: Array<SpendingCategoryResponse>;
};

/**
 * TransactionResponse
 */
export type TransactionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Occurred On
     */
    occurred_on: string;
    /**
     * Posted On
     */
    posted_on?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Merchant Name
     */
    merchant_name?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    status: TransactionStatus;
    type: TransactionType;
    /**
     * Postings
     */
    postings: Array<PostingResponse>;
    /**
     * Created On
     */
    created_on: string;
    /**
     * Updated On
     */
    updated_on: string;
};

/**
 * TransactionStatus
 */
export type TransactionStatus = 'pending' | 'posted' | 'void';

/**
 * TransactionType
 */
export type TransactionType = 'expense' | 'income' | 'transfer' | 'adjustment';

/**
 * UpdateAccountProfileRequest
 */
export type UpdateAccountProfileRequest = {
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Color Key
     */
    color_key?: string | null;
};

/**
 * UpdateIncomeCategoryRequest
 */
export type UpdateIncomeCategoryRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * UpdateSpendingCategoryRequest
 */
export type UpdateSpendingCategoryRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SystemGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type SystemGetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type SystemGetHealthResponse = SystemGetHealthResponses[keyof SystemGetHealthResponses];

export type AccountsListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/accounts';
};

export type AccountsListAccountsResponses = {
    /**
     * Response Accounts-List Accounts
     * Successful Response
     */
    200: Array<AccountResponse>;
};

export type AccountsListAccountsResponse = AccountsListAccountsResponses[keyof AccountsListAccountsResponses];

export type AccountsCreateAccountData = {
    body: CreateAccountRequest;
    path?: never;
    query?: never;
    url: '/api/v1/accounts';
};

export type AccountsCreateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsCreateAccountError = AccountsCreateAccountErrors[keyof AccountsCreateAccountErrors];

export type AccountsCreateAccountResponses = {
    /**
     * Successful Response
     */
    201: AccountResponse;
};

export type AccountsCreateAccountResponse = AccountsCreateAccountResponses[keyof AccountsCreateAccountResponses];

export type AccountsGetAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsGetAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsGetAccountError = AccountsGetAccountErrors[keyof AccountsGetAccountErrors];

export type AccountsGetAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsGetAccountResponse = AccountsGetAccountResponses[keyof AccountsGetAccountResponses];

export type AccountsUpdateAccountProfileData = {
    body: UpdateAccountProfileRequest;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsUpdateAccountProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsUpdateAccountProfileError = AccountsUpdateAccountProfileErrors[keyof AccountsUpdateAccountProfileErrors];

export type AccountsUpdateAccountProfileResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsUpdateAccountProfileResponse = AccountsUpdateAccountProfileResponses[keyof AccountsUpdateAccountProfileResponses];

export type AccountsArchiveAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}/archive';
};

export type AccountsArchiveAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsArchiveAccountError = AccountsArchiveAccountErrors[keyof AccountsArchiveAccountErrors];

export type AccountsArchiveAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsArchiveAccountResponse = AccountsArchiveAccountResponses[keyof AccountsArchiveAccountResponses];

export type SpendingCategoriesListSpendingCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/spending-categories';
};

export type SpendingCategoriesListSpendingCategoriesResponses = {
    /**
     * Response Spending-Categories-List Spending Categories
     * Successful Response
     */
    200: Array<SpendingCategoryResponse>;
};

export type SpendingCategoriesListSpendingCategoriesResponse = SpendingCategoriesListSpendingCategoriesResponses[keyof SpendingCategoriesListSpendingCategoriesResponses];

export type SpendingCategoriesCreateSpendingCategoryData = {
    body: CreateSpendingCategoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/spending-categories';
};

export type SpendingCategoriesCreateSpendingCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpendingCategoriesCreateSpendingCategoryError = SpendingCategoriesCreateSpendingCategoryErrors[keyof SpendingCategoriesCreateSpendingCategoryErrors];

export type SpendingCategoriesCreateSpendingCategoryResponses = {
    /**
     * Successful Response
     */
    201: SpendingCategoryResponse;
};

export type SpendingCategoriesCreateSpendingCategoryResponse = SpendingCategoriesCreateSpendingCategoryResponses[keyof SpendingCategoriesCreateSpendingCategoryResponses];

export type SpendingCategoriesUpdateSpendingCategoryData = {
    body: UpdateSpendingCategoryRequest;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/spending-categories/{category_id}';
};

export type SpendingCategoriesUpdateSpendingCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpendingCategoriesUpdateSpendingCategoryError = SpendingCategoriesUpdateSpendingCategoryErrors[keyof SpendingCategoriesUpdateSpendingCategoryErrors];

export type SpendingCategoriesUpdateSpendingCategoryResponses = {
    /**
     * Successful Response
     */
    200: SpendingCategoryResponse;
};

export type SpendingCategoriesUpdateSpendingCategoryResponse = SpendingCategoriesUpdateSpendingCategoryResponses[keyof SpendingCategoriesUpdateSpendingCategoryResponses];

export type IncomeCategoriesListIncomeCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/income-categories';
};

export type IncomeCategoriesListIncomeCategoriesResponses = {
    /**
     * Response Income-Categories-List Income Categories
     * Successful Response
     */
    200: Array<IncomeCategoryResponse>;
};

export type IncomeCategoriesListIncomeCategoriesResponse = IncomeCategoriesListIncomeCategoriesResponses[keyof IncomeCategoriesListIncomeCategoriesResponses];

export type IncomeCategoriesCreateIncomeCategoryData = {
    body: CreateIncomeCategoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/income-categories';
};

export type IncomeCategoriesCreateIncomeCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IncomeCategoriesCreateIncomeCategoryError = IncomeCategoriesCreateIncomeCategoryErrors[keyof IncomeCategoriesCreateIncomeCategoryErrors];

export type IncomeCategoriesCreateIncomeCategoryResponses = {
    /**
     * Successful Response
     */
    201: IncomeCategoryResponse;
};

export type IncomeCategoriesCreateIncomeCategoryResponse = IncomeCategoriesCreateIncomeCategoryResponses[keyof IncomeCategoriesCreateIncomeCategoryResponses];

export type IncomeCategoriesUpdateIncomeCategoryData = {
    body: UpdateIncomeCategoryRequest;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/income-categories/{category_id}';
};

export type IncomeCategoriesUpdateIncomeCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IncomeCategoriesUpdateIncomeCategoryError = IncomeCategoriesUpdateIncomeCategoryErrors[keyof IncomeCategoriesUpdateIncomeCategoryErrors];

export type IncomeCategoriesUpdateIncomeCategoryResponses = {
    /**
     * Successful Response
     */
    200: IncomeCategoryResponse;
};

export type IncomeCategoriesUpdateIncomeCategoryResponse = IncomeCategoriesUpdateIncomeCategoryResponses[keyof IncomeCategoriesUpdateIncomeCategoryResponses];

export type TransactionsListTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Account Id
         */
        account_id?: string | null;
    };
    url: '/api/v1/transactions';
};

export type TransactionsListTransactionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsListTransactionsError = TransactionsListTransactionsErrors[keyof TransactionsListTransactionsErrors];

export type TransactionsListTransactionsResponses = {
    /**
     * Response Transactions-List Transactions
     * Successful Response
     */
    200: Array<TransactionResponse>;
};

export type TransactionsListTransactionsResponse = TransactionsListTransactionsResponses[keyof TransactionsListTransactionsResponses];

export type TransactionsCreateTransactionData = {
    body: CreateTransactionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/transactions';
};

export type TransactionsCreateTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsCreateTransactionError = TransactionsCreateTransactionErrors[keyof TransactionsCreateTransactionErrors];

export type TransactionsCreateTransactionResponses = {
    /**
     * Successful Response
     */
    201: TransactionResponse;
};

export type TransactionsCreateTransactionResponse = TransactionsCreateTransactionResponses[keyof TransactionsCreateTransactionResponses];

export type TransactionsGetTransactionData = {
    body?: never;
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/api/v1/transactions/{transaction_id}';
};

export type TransactionsGetTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsGetTransactionError = TransactionsGetTransactionErrors[keyof TransactionsGetTransactionErrors];

export type TransactionsGetTransactionResponses = {
    /**
     * Successful Response
     */
    200: TransactionResponse;
};

export type TransactionsGetTransactionResponse = TransactionsGetTransactionResponses[keyof TransactionsGetTransactionResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};