// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccountResponse
 */
export type AccountResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Currency
     */
    currency: string;
    current_balance: MoneyResponse;
    status: AccountStatus;
    /**
     * Color Key
     */
    color_key?: string | null;
    /**
     * Opened On
     */
    opened_on: string;
    /**
     * Closed On
     */
    closed_on?: string | null;
    /**
     * Created On
     */
    created_on: string;
    /**
     * Updated On
     */
    updated_on: string;
};

/**
 * AccountStatus
 */
export type AccountStatus = 'active' | 'closed';

/**
 * AccountType
 */
export type AccountType = 'card' | 'cash' | 'bank' | 'wallet' | 'platform' | 'savings' | 'other';

/**
 * CreateAccountRequest
 */
export type CreateAccountRequest = {
    /**
     * Name
     */
    name: string;
    type?: AccountType;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Current Balance Minor
     */
    current_balance_minor?: number;
    /**
     * Opened On
     */
    opened_on?: string | null;
    /**
     * Color Key
     */
    color_key?: string | null;
};

/**
 * CreateSpendingCategoryRequest
 */
export type CreateSpendingCategoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * App Name
     */
    app_name: string;
    /**
     * Environment
     */
    environment: string;
};

/**
 * MoneyRequest
 */
export type MoneyRequest = {
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Currency
     */
    currency: string;
};

/**
 * MoneyResponse
 */
export type MoneyResponse = {
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Currency
     */
    currency: string;
};

/**
 * SpendingCategoryResponse
 */
export type SpendingCategoryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Children
     */
    children?: Array<SpendingCategoryResponse>;
};

/**
 * UpdateAccountProfileRequest
 */
export type UpdateAccountProfileRequest = {
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Color Key
     */
    color_key?: string | null;
};

/**
 * UpdateSpendingCategoryRequest
 */
export type UpdateSpendingCategoryRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SystemGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type SystemGetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type SystemGetHealthResponse = SystemGetHealthResponses[keyof SystemGetHealthResponses];

export type AccountsListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/accounts';
};

export type AccountsListAccountsResponses = {
    /**
     * Response Accounts-List Accounts
     * Successful Response
     */
    200: Array<AccountResponse>;
};

export type AccountsListAccountsResponse = AccountsListAccountsResponses[keyof AccountsListAccountsResponses];

export type AccountsCreateAccountData = {
    body: CreateAccountRequest;
    path?: never;
    query?: never;
    url: '/api/v1/accounts';
};

export type AccountsCreateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsCreateAccountError = AccountsCreateAccountErrors[keyof AccountsCreateAccountErrors];

export type AccountsCreateAccountResponses = {
    /**
     * Successful Response
     */
    201: AccountResponse;
};

export type AccountsCreateAccountResponse = AccountsCreateAccountResponses[keyof AccountsCreateAccountResponses];

export type AccountsGetAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsGetAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsGetAccountError = AccountsGetAccountErrors[keyof AccountsGetAccountErrors];

export type AccountsGetAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsGetAccountResponse = AccountsGetAccountResponses[keyof AccountsGetAccountResponses];

export type AccountsUpdateAccountProfileData = {
    body: UpdateAccountProfileRequest;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsUpdateAccountProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsUpdateAccountProfileError = AccountsUpdateAccountProfileErrors[keyof AccountsUpdateAccountProfileErrors];

export type AccountsUpdateAccountProfileResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsUpdateAccountProfileResponse = AccountsUpdateAccountProfileResponses[keyof AccountsUpdateAccountProfileResponses];

export type AccountsDepositToAccountData = {
    body: MoneyRequest;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}/deposits';
};

export type AccountsDepositToAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsDepositToAccountError = AccountsDepositToAccountErrors[keyof AccountsDepositToAccountErrors];

export type AccountsDepositToAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsDepositToAccountResponse = AccountsDepositToAccountResponses[keyof AccountsDepositToAccountResponses];

export type AccountsWithdrawFromAccountData = {
    body: MoneyRequest;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}/withdrawals';
};

export type AccountsWithdrawFromAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsWithdrawFromAccountError = AccountsWithdrawFromAccountErrors[keyof AccountsWithdrawFromAccountErrors];

export type AccountsWithdrawFromAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsWithdrawFromAccountResponse = AccountsWithdrawFromAccountResponses[keyof AccountsWithdrawFromAccountResponses];

export type AccountsCloseAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}/close';
};

export type AccountsCloseAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsCloseAccountError = AccountsCloseAccountErrors[keyof AccountsCloseAccountErrors];

export type AccountsCloseAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type AccountsCloseAccountResponse = AccountsCloseAccountResponses[keyof AccountsCloseAccountResponses];

export type SpendingCategoriesListSpendingCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/spending-categories';
};

export type SpendingCategoriesListSpendingCategoriesResponses = {
    /**
     * Response Spending-Categories-List Spending Categories
     * Successful Response
     */
    200: Array<SpendingCategoryResponse>;
};

export type SpendingCategoriesListSpendingCategoriesResponse = SpendingCategoriesListSpendingCategoriesResponses[keyof SpendingCategoriesListSpendingCategoriesResponses];

export type SpendingCategoriesCreateSpendingCategoryData = {
    body: CreateSpendingCategoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/spending-categories';
};

export type SpendingCategoriesCreateSpendingCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpendingCategoriesCreateSpendingCategoryError = SpendingCategoriesCreateSpendingCategoryErrors[keyof SpendingCategoriesCreateSpendingCategoryErrors];

export type SpendingCategoriesCreateSpendingCategoryResponses = {
    /**
     * Successful Response
     */
    201: SpendingCategoryResponse;
};

export type SpendingCategoriesCreateSpendingCategoryResponse = SpendingCategoriesCreateSpendingCategoryResponses[keyof SpendingCategoriesCreateSpendingCategoryResponses];

export type SpendingCategoriesUpdateSpendingCategoryData = {
    body: UpdateSpendingCategoryRequest;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/spending-categories/{category_id}';
};

export type SpendingCategoriesUpdateSpendingCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpendingCategoriesUpdateSpendingCategoryError = SpendingCategoriesUpdateSpendingCategoryErrors[keyof SpendingCategoriesUpdateSpendingCategoryErrors];

export type SpendingCategoriesUpdateSpendingCategoryResponses = {
    /**
     * Successful Response
     */
    200: SpendingCategoryResponse;
};

export type SpendingCategoriesUpdateSpendingCategoryResponse = SpendingCategoriesUpdateSpendingCategoryResponses[keyof SpendingCategoriesUpdateSpendingCategoryResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};